# Don't print a new line at the start of the prompt
add_newline = false
command_timeout = 2000

# Can replace the "â¯" symbol in the prompt
[character]
format = "$symbol "
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
vicmd_symbol = "[â®](bold green)"

[battery]
full_symbol = 'ðŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ðŸ’€ '
[[battery.display]]
threshold = 20
style = 'bold red'
[[battery.display]]
threshold = 60
style = 'bold yellow'

[cmd_duration]
disabled = true

[username]
style_user = 'yellow'
style_root = 'red bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](blue)@[$hostname](green) '
trim_at = '.companyname.com'
disabled = false

[directory]
format = '[\[$path\]]($style)[$read_only]($read_only_style) '
truncation_length = 0
style = "bold cyan"
disabled = false

[jobs]
symbol = "+"
threshold = 1

# Package module. Currently supports npm, cargo, poetry, composer, gradle, julia and mix
[package]
symbol = "ðŸŽ"
disabled = false

# Lua module.
[lua]
format = ' [î˜  $version](bold blue)'

[nodejs]
format = ' [îœ˜ $version](bold green)'

[c]
format = ' [ó°™± $version]($style)'

# [git_status]
# conflicted = 'âš”'
# ahead = 'â‡¢'
# behind = 'â‡ '
# diverged = 'ï‚'
# up_to_date = 'âœ“'
# untracked = 'î¯ƒ'
# stashed = 'ðŸ“¦'
# modified = 'ðŸ“'
# staged = '[++\($count\)](green)'
# renamed = 'ó°‘•'
# deleted = 'ðŸ—‘'

[custom.git_server]
description = "Display symbol for remote Git server"
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    echo " î™› "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    echo " î™œ "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    echo " îœƒ "
else
    echo " î¯ƒ "
fi
"""
when = 'git rev-parse --is-inside-work-tree'
